var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.inherits=function(a,e){function d(){}d.prototype=e.prototype;a.superClass_=e.prototype;a.prototype=new d;a.prototype.constructor=a;for(var b in e)if(Object.defineProperties){var c=Object.getOwnPropertyDescriptor(e,b);c&&Object.defineProperty(a,b,c)}else a[b]=e[b]};var fs=require("fs"),EventEmitter=require("events"),Emitter=function(a){return EventEmitter.apply(this,arguments)||this};$jscomp.inherits(Emitter,EventEmitter);var emitter=new Emitter;
emitter.on("error",function(a){logger.error("Unexpected error on emitter",a);process.exit(1)});
var pageDimensions={p:{a2:{width:1648,footerY:280,height:1191},a3:{width:842,footerY:410,height:1191},a4:{width:595,footerY:280,height:842},a5:{width:420,footerY:200,height:595},letter:{width:612,footerY:270,height:792},legal:{width:612,footerY:340,height:1008},ledger_tabloid:{width:792,footerY:340,height:1224}},l:{a2:{width:1648,footerY:280,height:1191},a3:{width:1191,footerY:200,height:1191},a4:{width:842,footerY:200,height:595},a5:{width:595,footerY:200,height:420},letter:{width:792,footerY:200,
height:612},legal:{width:1008,footerY:200,height:612},ledger_tabloid:{width:1224,footerY:340,height:792}}},_exportTabletoPdf=function(a,e,d,b,c,l,f,h,k,n){var r=h.orientation,p=h.format,g=require("./plugins/tabletab"),q=require("./plugins/tableprocessing"),w=require("./plugins/tabletabtext");var m=[255,255,255];var v=[0,0,0],z=[];b+=55;c.showMetadata&&(b=130);m=g().getPDFDimensions(f[r][p].width,f[r][p].height,100,20,b,p,r,c.showMetadata,l.toString(),c.footerText);f=m.maxRows;g=m.maxCols;d.cellInitialize();
d.setFontSize(10);p=a.splice(0,1)[0];r=a.splice(0,1)[0];c.isWrapColHeadersChecked&&(a=w().markColumnHeaderRowsForExpansion(d,a,p),a=w().expandColumnHeaderRowsAndWrapText(d,a,p),p=a.splice(0,1)[0]);c.isWrapRowHeadersChecked&&(a=w().markRowHeaderRowsForExpansion(d,a,p,r),a=w().expandHeaderRowsAndWrapText(d,a,p,r));a=q().repeatColumnHeaders(a,f,p);a=q().repeatRowHeaders(a,g,r);for(q=0;q<a.length;q+=f){var A=1;a[q].length>g&&(A=Math.ceil((a[q].length-r)/g));for(var B=w=0;B<A;B++){for(var t=0;t<f&&t<a.length;t++){var D=
t+q;if(D>=a.length)break;for(var C=0;C<g;C++){m=w+C;if(m>=a[q].length)break;var x=a[D][m];var y=""===x.text?" ":x.text;var u=function(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?parseInt(a[1],16)+","+parseInt(a[2],16)+","+parseInt(a[3],16):null};m=u(x.color);m=m.split(",");for(v=0;v<m.length;v++)m[v]=parseInt(m[v]);u=u(x.fontColor);v=u.split(",");for(u=0;u<v.length;u++)v[u]=parseInt(v[u]);var F=x.symbol+x.alertLvl;var E=x.align;var G=x.isSpan;var H=x.rowSpanPos;var I=x.colSpanPos;
d.setFillColor.apply(d,m);d.setTextColor.apply(d,v);d.setDrawColor(0,0,0,.4);u="true"===x.isBold?!0:!1;!0===u?d.setFontStyle("bold"):d.setFontStyle("normal");m=!1;x.isSpan&&t===f-1&&(m=!0);d.printingHeaderRow=!0;t+1<p?(0===t&&20<y.length&&(35<y.length&&(y=y.substring(0,35),y+="..."),y=d.splitTextToSize(y,95)),"true"===G.toLowerCase()?z.push([10,b,100,20,y,t,E,u,""[F],H,I,m]):z.push([10,b,100,20,y,t,E,u])):(m="true"===G.toLowerCase()?[10,b,100,20,y,t,E,u,""[F],H,I,m]:[10,b,100,20,y,t,E,u],d.spanCell.apply(d,
m))}t<p&&(d.setTableHeaderRow(z),d.printHeaderRow(t,u),z=[])}c.showMetadata&&addPdfMetadata(d,e,c.selectedPageSize,c.pageOrientation,c.pdfHeaderTextDate,c.pdfHeaderTextQuery,c.pdfHeaderTextVariables,c.pdfHeaderTextDynamic,c.pdfHeaderTextStatic);if(t+q<a.length||1!==A&&B<=A-2)d.cellAddPage(),addHeaderFooter(d,(l+B+1).toString(),h,k,n);w+=g;z=[]}}return A},finalPdf=function(){var a=process.argv[2];require("fs").readFile(a,"utf8",function(e,d){try{e&&emitter.emit("error",e);var b=JSON.parse(d),c=b.content,
l=b.header,f=b.footer,h=b.pdf_prop;"use strict";var k=new (require("jsdom").JSDOM)("\x3c!DOCTYPE html\x3e\x3cp\x3e\x3c/p\x3e");global.document=k.window.document;global.window=k.window;global.navigator=window.navigator;var n=require("fs"),r=require("jspdf");require("./plugins/svgToPdf");require("./plugins/jspdf-plugin");require("base64-img");var p=require("./libs/canvg_context2d/canvg"),g=new r(h.orientation,"pt",h.format);e=1;var q=addHeaderFooter(g,e.toString(),h,l,f);var w=g.canvas;w.width=595;
w.height=500;var m=w.getContext("2d");m.ignoreClearRect=!0;m.translate(0,q+50);for(var v in c)switch(c[v].type){case "image":g.addImage(c[v].data,"PNG",40,q+50,0,0);g.addPage();e++;q=addHeaderFooter(g,e.toString(),h,l,f);break;case "svg":p(w,c[v].data,{ignoreMouse:!0,ignoreAnimation:!0,ignoreDimensions:!0});g.addPage();e++;q=addHeaderFooter(g,e.toString(),h,l,f);break;case "table":var z=JSON.parse(c[v].data)[0],A=_exportTabletoPdf(z.TABLE_1_control,"TABLE_1_control",g,q,{},e,pageDimensions,h,l,f);
e+=A;g.addPage();q=addHeaderFooter(g,e.toString(),h,l,f)}g.deletePage(e);var B=g.output("arraybuffer"),t=Buffer.from(B),D=Uint8Array.from(t);n.appendFile(a+".pdf",new Buffer(D),function(a){a?(console.log(a),process.exit(1)):(console.log("PDF created"),process.exit(0))})}catch(C){emitter.emit("error",C)}})},addHeaderFooter=function(a,e,d,b,c){var l=0;if(""!==b.image){var f=getStartPosition(d,!1,b.image_align,201,72);f.y=0+parseInt(d.top_margin);a.addImage(b.image,"PNG",f.x,f.y,0,0);l=f.y}if(""!==b.text){a.setFontSize(b.text_size);
var h=getStartPosition(d,!1,b.text_align,b.text,b.text_size);b.image_align===b.text_align&""!==b.image&&(h.y=f.y+72);a.text(h.x,h.y,b.text);l=l>h.y?l:h.y}if("true"===b.add_date){var k=(new Date).toDateString();a.setFontSize(b.date_size);var n=getStartPosition(d,!1,b.date_align,k,b.date_size);b.date_align===b.text_align&&""!==b.text?n.y=h.y+parseInt(b.text_size):b.date_align===b.image_align&&""!==b.image&&(n.y=f.y+72);a.text(n.x,n.y,k);l=l>n.y?l:n.y}"true"===b.add_page_no&&(a.setFontSize(b.page_no_size),
k=getStartPosition(d,!1,b.page_no_align,e,b.page_no_size),b.page_no_align===b.date_align&&"true"===b.add_date?k.y=n.y+parseInt(b.date_size):b.page_no_align===b.text_align&&""!==b.text?k.y=h.y+parseInt(b.text_size):b.page_no_align===b.image_align&&""!==b.image&&(k.y=f.y+72),a.text(k.x,k.y,e),l=l>k.y?l:k.y);if("true"===c.add_page_no){a.setFontSize(c.page_no_size);var r=getStartPosition(d,!0,c.page_no_align,e,c.page_no_size);a.text(r.x,r.y,e)}if("true"===c.add_date){k=(new Date).toDateString();a.setFontSize(c.date_size);
var p=getStartPosition(d,!0,c.date_align,k,c.date_size);c.date_align===c.page_no_align&&(p.y=r.y-c.date_size-5);a.text(p.x,p.y,k)}if(""!==c.text){a.setFontSize(c.text_size);var g=getStartPosition(d,!0,c.text_align,c.text,c.text_size);c.text_align===c.date_align?g.y=p.y-c.text_size-5:c.text_align===c.page_no_align&&(g.y=r.y-c.text_size-5);a.text(g.x,g.y,c.text)}""!==c.image&&(e=getStartPosition(d,!0,c.image_align,201,72),f.y=pageDimensions[d.orientation][d.format].height-(parseInt(d.top_margin)+72),
c.image_align===c.text_align?e.y=g.y-72-5:c.image_align===c.date_align?e.y=p.y-72-5:c.image_align===c.page_no_align&&(e.y=r-72-5),a.addImage(b.image,"PNG",e.x,e.y,0,0));return l},getStartPosition=function(a,e,d,b,c,l){var f=a.orientation,h=a.format,k=parseInt(a.top_margin);a=parseInt(a.left_margin);var n=pageDimensions[f][h].width;l?e={maxLen:n-2*a,totalWidth:n,y:e?pageDimensions[f][h].height-k:k}:(e={maxLen:(n-2*a-6)/3,y:e?"number"==typeof b?pageDimensions[f][h].height-k-parseInt(c):pageDimensions[f][h].height-
k-parseInt(c)-5:parseInt(k+parseInt(c))},"center"==d?(n=n-2*a-6,d=b.length,e.x="number"==typeof b?n/2-b/2+a+20:n/2-.45*d*c/2):"right"==d?(d=b.length,e.x=n-2*a-6-.45*d*c):e.x=a+10);return e};finalPdf();
