var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.inherits=function(a,e){function d(){}d.prototype=e.prototype;a.superClass_=e.prototype;a.prototype=new d;a.prototype.constructor=a;for(var b in e)if(Object.defineProperties){var c=Object.getOwnPropertyDescriptor(e,b);c&&Object.defineProperty(a,b,c)}else a[b]=e[b]};var fs=require("fs"),EventEmitter=require("events"),Emitter=function(a){return EventEmitter.apply(this,arguments)||this};$jscomp.inherits(Emitter,EventEmitter);var emitter=new Emitter;
emitter.on("error",function(a){console.log("Unexpected error on emitter",a);process.exit(1)});
var pageDimensions={p:{a2:{width:1648,footerY:280,height:1191},a3:{width:842,footerY:410,height:1191},a4:{width:595,footerY:280,height:842},a5:{width:420,footerY:200,height:595},letter:{width:612,footerY:270,height:792},legal:{width:612,footerY:340,height:1008},ledger_tabloid:{width:792,footerY:340,height:1224}},l:{a2:{width:1648,footerY:280,height:1191},a3:{width:1191,footerY:200,height:1191},a4:{width:842,footerY:200,height:595},a5:{width:595,footerY:200,height:420},letter:{width:792,footerY:200,
height:612},legal:{width:1008,footerY:200,height:612},ledger_tabloid:{width:1224,footerY:340,height:792}}},_exportTabletoPdf=function(a,e,d,b,c,l,g,f,k,n){var t=f.orientation,p=f.format,h=require("../plugins/tabletab"),q=require("../plugins/tableprocessing"),y=require("../plugins/tabletabtext");var m=[255,255,255];var v=[0,0,0],z=[];b+=55;c.showMetadata&&(b=130);m=h().getPDFDimensions(g[t][p].width,g[t][p].height,100,20,b,p,t,c.showMetadata,l.toString(),c.footerText);g=m.maxRows;h=m.maxCols;d.cellInitialize();
d.setFontSize(10);p=a.splice(0,1)[0];t=a.splice(0,1)[0];c.isWrapColHeadersChecked&&(a=y().markColumnHeaderRowsForExpansion(d,a,p),a=y().expandColumnHeaderRowsAndWrapText(d,a,p),p=a.splice(0,1)[0]);c.isWrapRowHeadersChecked&&(a=y().markRowHeaderRowsForExpansion(d,a,p,t),a=y().expandHeaderRowsAndWrapText(d,a,p,t));a=q().repeatColumnHeaders(a,g,p);a=q().repeatRowHeaders(a,h,t);for(q=0;q<a.length;q+=g){var A=1;a[q].length>h&&(A=Math.ceil((a[q].length-t)/h));for(var B=y=0;B<A;B++){for(var u=0;u<g&&u<a.length;u++){var E=
u+q;if(E>=a.length)break;for(var C=0;C<h;C++){m=y+C;if(m>=a[q].length)break;var w=a[E][m];var x=""===w.text?" ":w.text;var r=function(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?parseInt(a[1],16)+","+parseInt(a[2],16)+","+parseInt(a[3],16):null};m=r(w.color);m=m.split(",");for(v=0;v<m.length;v++)m[v]=parseInt(m[v]);r=r(w.fontColor);v=r.split(",");for(r=0;r<v.length;r++)v[r]=parseInt(v[r]);var F=w.symbol+w.alertLvl;var D=w.align;var G=w.isSpan;var H=w.rowSpanPos;var I=w.colSpanPos;
d.setFillColor.apply(d,m);d.setTextColor.apply(d,v);d.setDrawColor(0,0,0,.4);r="true"===w.isBold?!0:!1;!0===r?d.setFontStyle("bold"):d.setFontStyle("normal");m=!1;w.isSpan&&u===g-1&&(m=!0);d.printingHeaderRow=!0;u+1<p?(0===u&&20<x.length&&(35<x.length&&(x=x.substring(0,35),x+="..."),x=d.splitTextToSize(x,95)),"true"===G.toLowerCase()?z.push([10,b,100,20,x,u,D,r,""[F],H,I,m]):z.push([10,b,100,20,x,u,D,r])):(m="true"===G.toLowerCase()?[10,b,100,20,x,u,D,r,""[F],H,I,m]:[10,b,100,20,x,u,D,r],d.spanCell.apply(d,
m))}u<p&&(d.setTableHeaderRow(z),d.printHeaderRow(u,r),z=[])}c.showMetadata&&addPdfMetadata(d,e,c.selectedPageSize,c.pageOrientation,c.pdfHeaderTextDate,c.pdfHeaderTextQuery,c.pdfHeaderTextVariables,c.pdfHeaderTextDynamic,c.pdfHeaderTextStatic);if(u+q<a.length||1!==A&&B<=A-2)d.cellAddPage(),addHeaderFooter(d,(l+B+1).toString(),f,k,n);y+=h;z=[]}}return A},finalPdf=function(){var a=process.argv[2];require("fs").readFile(a,"utf8",function(e,d){try{e&&emitter.emit("error",e);var b=JSON.parse(d),c=b.content,
l=b.header,g=b.footer,f=b.pdfProp;"use strict";var k=new (require("jsdom").JSDOM)("\x3c!DOCTYPE html\x3e\x3cp\x3e\x3c/p\x3e");global.document=k.window.document;global.window=k.window;global.navigator=window.navigator;var n=require("fs"),t=require("jspdf");require("../plugins/svgToPdf");require("../plugins/jspdf-plugin");require("base64-img");var p=require("../libs/canvg_context2d/canvg");console.log(f);var h=new t(f.orientation,"pt",f.format);e=1;var q=addHeaderFooter(h,e.toString(),f,l,g);var y=h.canvas;
y.width=pageDimensions[f.orientation][f.format].width;y.height=pageDimensions[f.orientation][f.format].height;console.log(pageDimensions[f.orientation][f.format].width);var m=y.getContext("2d");m.ignoreClearRect=!0;m.translate(0,q+50);for(var v in c)switch(c[v].type){case "image":var z=c[v].data,A=pageDimensions[f.orientation][f.format].width-2*parseInt(f.leftMargin,10);h.addImage(z,"PNG",parseInt(f.leftMargin,10),q,A,0);h.addPage();e++;q=addHeaderFooter(h,e.toString(),f,l,g);break;case "svg":var B=
c[v].data,u=pageDimensions[f.orientation][f.format].width-2*parseInt(f.leftMargin,10);p(y,B,{ignoreMouse:!0,ignoreAnimation:!0,ignoreDimensions:!0,scaleWidth:u,offsetX:parseInt(f.leftMargin,10),offsetY:q});h.addPage();e++;q=addHeaderFooter(h,e.toString(),f,l,g);break;case "table":var E=JSON.parse(c[v].data);console.log("table start");var C=E[0];console.log(C);var w=_exportTabletoPdf(C.TABLE_1_control,"TABLE_1_control",h,q,{},e,pageDimensions,f,l,g);e+=w;h.addPage();q=addHeaderFooter(h,e.toString(),
f,l,g);console.log("table end")}h.deletePage(e);var x=h.output("arraybuffer"),r=Buffer.from(x),F=Uint8Array.from(r);n.appendFile(a+".pdf",new Buffer(F),function(a){a?(console.log(a),process.exit(1)):(console.log("PDF created"),process.exit(0))})}catch(D){emitter.emit("error",D)}})},addHeaderFooter=function(a,e,d,b,c){var l=0;if(""!==b.image){var g=getStartPosition(d,!1,b.imageAlign,201,72);g.y=0+parseInt(d.topMargin);a.addImage(b.image,"PNG",g.x,g.y,0,0);l=g.y}if(""!==b.text){a.setFontSize(b.textSize);
var f=getStartPosition(d,!1,b.textAlign,b.text,b.textSize);b.imageAlign===b.textAlign&""!==b.image&&(f.y=g.y+72);a.text(f.x,f.y,b.text);l=l>f.y?l:f.y}if("true"===b.addDate){var k=(new Date).toDateString();a.setFontSize(b.dateSize);var n=getStartPosition(d,!1,b.dateAlign,k,b.dateSize);b.dateAlign===b.textAlign&&""!==b.text?n.y=f.y+parseInt(b.textSize):b.dateAlign===b.imageAlign&&""!==b.image&&(n.y=g.y+72);a.text(n.x,n.y,k);l=l>n.y?l:n.y}"true"===b.addPageNo&&(a.setFontSize(b.pageNoSize),k=getStartPosition(d,
!1,b.pageNoAlign,e,b.pageNoSize),b.pageNoAlign===b.dateAlign&&"true"===b.addDate?k.y=n.y+parseInt(b.dateSize):b.pageNoAlign===b.textAlign&&""!==b.text?k.y=f.y+parseInt(b.textSize):b.pageNoAlign===b.imageAlign&&""!==b.image&&(k.y=g.y+72),a.text(k.x,k.y,e),l=l>k.y?l:k.y);if("true"===c.addPageNo){a.setFontSize(c.pageNoSize);var t=getStartPosition(d,!0,c.pageNoAlign,e,c.pageNoSize);a.text(t.x,t.y,e)}if("true"===c.addDate){k=(new Date).toDateString();a.setFontSize(c.dateSize);var p=getStartPosition(d,
!0,c.dateAlign,k,c.dateSize);c.dateAlign===c.pageNoAlign&&(p.y=t.y-c.dateSize-5);a.text(p.x,p.y,k)}if(""!==c.text){a.setFontSize(c.textSize);var h=getStartPosition(d,!0,c.textAlign,c.text,c.textSize);c.textAlign===c.dateAlign?h.y=p.y-c.textSize-5:c.textAlign===c.pageNoAlign&&(h.y=t.y-c.textSize-5);a.text(h.x,h.y,c.text)}""!==c.image&&(e=getStartPosition(d,!0,c.imageAlign,201,72),g.y=pageDimensions[d.orientation][d.format].height-(parseInt(d.topMargin)+72),c.imageAlign===c.textAlign?e.y=h.y-72-5:c.imageAlign===
c.dateAlign?e.y=p.y-72-5:c.image_align===c.pageNoAlign&&(e.y=t-72-5),a.addImage(b.image,"PNG",e.x,e.y,0,0));return l},getStartPosition=function(a,e,d,b,c,l){var g=a.orientation,f=a.format,k=parseInt(a.topMargin);a=parseInt(a.leftMargin);var n=pageDimensions[g][f].width;l?e={maxLen:n-2*a,totalWidth:n,y:e?pageDimensions[g][f].height-k:k}:(e={maxLen:(n-2*a-6)/3,y:e?"number"==typeof b?pageDimensions[g][f].height-k-parseInt(c):pageDimensions[g][f].height-k-parseInt(c)-5:parseInt(k+parseInt(c))},"center"==
d?(n=n-2*a-6,d=b.length,e.x="number"==typeof b?n/2-b/2+a+20:n/2-.45*d*c/2):"right"==d?(d=b.length,e.x=n-2*a-6-.45*d*c):e.x=a+10);return e};finalPdf();
