var fs=require("fs"),pageDimensions={p:{a2:{width:1648,footerY:280,height:1191},a3:{width:842,footerY:410,height:1191},a4:{width:595,footerY:280,height:842},a5:{width:420,footerY:200,height:595},letter:{width:612,footerY:270,height:792},legal:{width:612,footerY:340,height:1008},ledger_tabloid:{width:792,footerY:340,height:1224}},l:{a2:{width:1648,footerY:280,height:1191},a3:{width:1191,footerY:200,height:1191},a4:{width:842,footerY:200,height:595},a5:{width:595,footerY:200,height:420},letter:{width:792,
footerY:200,height:612},legal:{width:1008,footerY:200,height:612},ledger_tabloid:{width:1224,footerY:340,height:792}}},_exportTabletoPdf=function(c,f,d,a,b,l,e,q,g,h){var n=q.orientation,k=q.format,m=require("./plugins/tabletab"),w=require("./plugins/tableprocessing"),y=require("./plugins/tabletabtext");var p=[255,255,255];var x=[0,0,0],z=[];a+=55;b.showMetadata&&(a=130);p=m().getPDFDimensions(e[n][k].width,e[n][k].height,100,20,a,k,n,b.showMetadata,l.toString(),b.footerText);e=p.maxRows;m=p.maxCols;
d.cellInitialize();d.setFontSize(10);k=c.splice(0,1)[0];n=c.splice(0,1)[0];b.isWrapColHeadersChecked&&(c=y().markColumnHeaderRowsForExpansion(d,c,k),c=y().expandColumnHeaderRowsAndWrapText(d,c,k),k=c.splice(0,1)[0]);b.isWrapRowHeadersChecked&&(c=y().markRowHeaderRowsForExpansion(d,c,k,n),c=y().expandHeaderRowsAndWrapText(d,c,k,n));c=w().repeatColumnHeaders(c,e,k);c=w().repeatRowHeaders(c,m,n);for(w=0;w<c.length;w+=e){var A=1;c[w].length>m&&(A=Math.ceil((c[w].length-n)/m));for(var B=y=0;B<A;B++){for(var t=
0;t<e&&t<c.length;t++){var E=t+w;if(E>=c.length)break;for(var D=0;D<m;D++){p=y+D;if(p>=c[w].length)break;var u=c[E][p];var v=""===u.text?" ":u.text;var r=function(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?parseInt(a[1],16)+","+parseInt(a[2],16)+","+parseInt(a[3],16):null};p=r(u.color);p=p.split(",");for(x=0;x<p.length;x++)p[x]=parseInt(p[x]);r=r(u.fontColor);x=r.split(",");for(r=0;r<x.length;r++)x[r]=parseInt(x[r]);var F=u.symbol+u.alertLvl;var C=u.align;var G=u.isSpan;var H=
u.rowSpanPos;var I=u.colSpanPos;d.setFillColor.apply(d,p);d.setTextColor.apply(d,x);d.setDrawColor(0,0,0,.4);r="true"===u.isBold?!0:!1;!0===r?d.setFontStyle("bold"):d.setFontStyle("normal");p=!1;u.isSpan&&t===e-1&&(p=!0);d.printingHeaderRow=!0;t+1<k?(0===t&&20<v.length&&(35<v.length&&(v=v.substring(0,35),v+="..."),v=d.splitTextToSize(v,95)),"true"===G.toLowerCase()?z.push([10,a,100,20,v,t,C,r,""[F],H,I,p]):z.push([10,a,100,20,v,t,C,r])):(p="true"===G.toLowerCase()?[10,a,100,20,v,t,C,r,""[F],H,I,p]:
[10,a,100,20,v,t,C,r],d.spanCell.apply(d,p))}t<k&&(d.setTableHeaderRow(z),d.printHeaderRow(t,r),z=[])}b.showMetadata&&addPdfMetadata(d,f,b.selectedPageSize,b.pageOrientation,b.pdfHeaderTextDate,b.pdfHeaderTextQuery,b.pdfHeaderTextVariables,b.pdfHeaderTextDynamic,b.pdfHeaderTextStatic);if(t+w<c.length||1!==A&&B<=A-2)d.cellAddPage(),addHeaderFooter(d,(l+B+1).toString(),q,g,h);y+=m;z=[]}}return A},finalPdf=function(){var c=process.argv[2];require("fs").readFile(c,"utf8",function(f,d){if(f)throw f;f=
JSON.parse(d);d=f.content;var a=f.header,b=f.footer,l=f.pdf_prop;console.log(f.header);"use strict";f=new (require("jsdom").JSDOM)("\x3c!DOCTYPE html\x3e\x3cp\x3eHello world\x3c/p\x3e");global.document=f.window.document;global.window=f.window;global.navigator=window.navigator;f=require("fs");var e=require("jspdf");require("./plugins/svgToPdf");require("./plugins/jspdf-plugin");require("base64-img");var q=require("./libs/canvg_context2d/canvg"),e=new e(l.orientation,"pt",l.format),g=1;var h=addHeaderFooter(e,
g.toString(),l,a,b);var n=e.canvas;n.width=595;n.height=500;var k=n.getContext("2d");k.ignoreClearRect=!0;k.translate(0,h+50);for(var m in d)switch(d[m].type){case "image":e.addImage(d[m].data,"PNG",40,h+50,0,0);e.addPage();g++;h=addHeaderFooter(e,g.toString(),l,a,b);break;case "svg":k=d[m].data;console.log(h+50);q(n,k,{ignoreMouse:!0,ignoreAnimation:!0,ignoreDimensions:!0});e.addPage();g++;h=addHeaderFooter(e,g.toString(),l,a,b);break;case "table":k=JSON.parse(d[m].data),console.log(k),h=_exportTabletoPdf(k[0].TABLE_1_control,
"TABLE_1_control",e,h,{},g,pageDimensions,l,a,b),g+=h,e.addPage(),h=addHeaderFooter(e,g.toString(),l,a,b)}e.deletePage(g);m=e.output("arraybuffer");m=Buffer.from(m);m=Uint8Array.from(m);f.appendFile("./export/"+c+".pdf",new Buffer(m),function(a){a?console.log(a):(console.log("PDF created"),process.exit(0))})})},addHeaderFooter=function(c,f,d,a,b){var l=0;if(""!==a.image){var e=getStartPosition(d,!1,a.image_align,201,72);e.y=0+parseInt(d.top_margin);c.addImage(a.image,"PNG",e.x,e.y,0,0);l=e.y}if(""!==
a.text){c.setFontSize(a.text_size);var q=getStartPosition(d,!1,a.text_align,a.text,a.text_size);a.image_align===a.text_align&""!==a.image&&(q.y=e.y+72);c.text(q.x,q.y,a.text);l=l>q.y?l:q.y}if("true"===a.add_date){var g=(new Date).toDateString();c.setFontSize(a.date_size);var h=getStartPosition(d,!1,a.date_align,g,a.date_size);a.date_align===a.text_align&&""!==a.text?h.y=q.y+parseInt(a.text_size):a.date_align===a.image_align&&""!==a.image&&(h.y=e.y+72);c.text(h.x,h.y,g);l=l>h.y?l:h.y}"true"===a.add_page_no&&
(c.setFontSize(a.page_no_size),g=getStartPosition(d,!1,a.page_no_align,f,a.page_no_size),a.page_no_align===a.date_align&&"true"===a.add_date?g.y=h.y+parseInt(a.date_size):a.page_no_align===a.text_align&&""!==a.text?g.y=q.y+parseInt(a.text_size):a.page_no_align===a.image_align&&""!==a.image&&(g.y=e.y+72),c.text(g.x,g.y,f),l=l>g.y?l:g.y);if("true"===b.add_page_no){c.setFontSize(b.page_no_size);var n=getStartPosition(d,!0,b.page_no_align,f,b.page_no_size);c.text(n.x,n.y,f)}if("true"===b.add_date){g=
(new Date).toDateString();c.setFontSize(b.date_size);var k=getStartPosition(d,!0,b.date_align,g,b.date_size);b.date_align===b.page_no_align&&(k.y=n.y-b.date_size-5);c.text(k.x,k.y,g)}if(""!==b.text){c.setFontSize(b.text_size);var m=getStartPosition(d,!0,b.text_align,b.text,b.text_size);b.text_align===b.date_align?m.y=k.y-b.text_size-5:b.text_align===b.page_no_align&&(m.y=n.y-b.text_size-5);c.text(m.x,m.y,b.text)}""!==b.image&&(f=getStartPosition(d,!0,b.image_align,201,72),e.y=pageDimensions[d.orientation][d.format].height-
(parseInt(d.top_margin)+72),b.image_align===b.text_align?f.y=m.y-72-5:b.image_align===b.date_align?f.y=k.y-72-5:b.image_align===b.page_no_align&&(f.y=n-72-5),c.addImage(a.image,"PNG",f.x,f.y,0,0));return l},getStartPosition=function(c,f,d,a,b,l){var e=c.orientation,q=c.format,g=parseInt(c.top_margin);c=parseInt(c.left_margin);var h=pageDimensions[e][q].width;l?f={maxLen:h-2*c,totalWidth:h,y:f?pageDimensions[e][q].height-g:g}:(f={maxLen:(h-2*c-6)/3,y:f?"number"==typeof a?pageDimensions[e][q].height-
g-parseInt(b):pageDimensions[e][q].height-g-parseInt(b)-5:parseInt(g+parseInt(b))},"center"==d?(h=h-2*c-6,d=a.length,f.x="number"==typeof a?h/2-a/2+c+20:h/2-.45*d*b/2):"right"==d?(d=a.length,f.x=h-2*c-6-.45*d*b):f.x=c+10);return f};finalPdf();
